# Theme configuration
theme: jekyll-theme-cayman
title: 5DAT
description: 5DAT notes & co
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/5DAT/
baseUrl: https://c0zen.github.io/5DAT/
